// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeaceInternational.Infrastructure;

#nullable disable

namespace PeaceInternational.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323105125_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentStaff")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileCodeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<string>("GuideName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndDateAD")
                        .HasColumnType("date");

                    b.Property<string>("EndDateBS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("StartDateAD")
                        .HasColumnType("date");

                    b.Property<string>("StartDateBS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FiscalYear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2077/03/31",
                            Name = "76/77",
                            StartDateAD = new DateTime(2019, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2076/04/01"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2021, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2078/03/31",
                            Name = "77/78",
                            StartDateAD = new DateTime(2020, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2077/04/01"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2022, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2079/03/32",
                            Name = "78/79",
                            StartDateAD = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2078/04/01"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2080/03/31",
                            Name = "79/80",
                            StartDateAD = new DateTime(2022, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2079/04/01"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2081/03/32",
                            Name = "80/81",
                            StartDateAD = new DateTime(2023, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2080/04/01"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2082/03/31",
                            Name = "81/82",
                            StartDateAD = new DateTime(2024, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2081/04/01"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2083/03/32",
                            Name = "82/83",
                            StartDateAD = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2082/04/01"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2027, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2084/03/32",
                            Name = "83/84",
                            StartDateAD = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2083/04/01"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2028, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2085/03/31",
                            Name = "84/85",
                            StartDateAD = new DateTime(2027, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2084/04/01"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2029, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2086/03/31",
                            Name = "85/86",
                            StartDateAD = new DateTime(2028, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2085/04/01"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2030, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2087/03/32",
                            Name = "86/87",
                            StartDateAD = new DateTime(2029, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2086/04/01"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2031, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2088/03/32",
                            Name = "87/88",
                            StartDateAD = new DateTime(2030, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2087/04/01"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateAD = new DateTime(2032, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateBS = "2089/03/31",
                            Name = "88/89",
                            StartDateAD = new DateTime(2031, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateBS = "2088/04/01"
                        });
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("FullDayRate")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal>("HalfDayRate")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("OverNight")
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Guide");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.HotelRoomRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AP")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("DoubleBed")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal>("ExtraBed")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("MAP")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("SingleBed")
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("HotelRoomRate");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("Dr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileCodeNo")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<string>("Guide")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsTicket")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<int?>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("TotalDue")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("Vehicle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FileCodeNo");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Particulars")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceDetail");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.SectorTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("TransportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("TransportId");

                    b.ToTable("SectorTransport");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.ServiceVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ArrivalFlight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartureFlight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ExchangeOrderNo")
                        .HasColumnType("longtext");

                    b.Property<string>("FileCodeNo")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("Services")
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FileCodeNo");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("HotelId");

                    b.ToTable("ServiceVoucher");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Tourcost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category3")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category4")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category5")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("DiscountAccomodation")
                        .HasColumnType("int");

                    b.Property<int>("DiscountTransportation")
                        .HasColumnType("int");

                    b.Property<int?>("GuideDaysEscort")
                        .HasColumnType("int");

                    b.Property<int?>("GuideDaysFullDay")
                        .HasColumnType("int");

                    b.Property<int?>("GuideDaysHalfDay")
                        .HasColumnType("int");

                    b.Property<int?>("GuideId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLuxury")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxPAX")
                        .HasColumnType("int");

                    b.Property<string>("MealType")
                        .HasColumnType("longtext");

                    b.Property<int>("MinPAX")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("Tourcost");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.TourcostDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Category1Cost")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal?>("Category2Cost")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal?>("Category3Cost")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal?>("Category4Cost")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal?>("Category5Cost")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("HotelAId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelBId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelCId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Sector1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Sector2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Sector3Id")
                        .HasColumnType("int");

                    b.Property<int>("TourcostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelAId");

                    b.HasIndex("HotelBId");

                    b.HasIndex("HotelCId");

                    b.HasIndex("Sector1Id");

                    b.HasIndex("Sector2Id");

                    b.HasIndex("Sector3Id");

                    b.HasIndex("TourcostId");

                    b.ToTable("TourcostDetail");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MaxPAX")
                        .HasColumnType("int");

                    b.Property<int>("MinPAX")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Transport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPAX = 2,
                            MinPAX = 1,
                            Name = "T1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPAX = 5,
                            MinPAX = 3,
                            Name = "T2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPAX = 9,
                            MinPAX = 6,
                            Name = "T3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPAX = 19,
                            MinPAX = 10,
                            Name = "T4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPAX = 24,
                            MinPAX = 20,
                            Name = "T5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "superadmin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPAX = 100,
                            MinPAX = 25,
                            Name = "T6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Customer", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.FiscalYear", "FiscalYear")
                        .WithMany("Customers")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.HotelRoomRate", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Hotel", "Hotel")
                        .WithOne("HotelRoomRate")
                        .HasForeignKey("PeaceInternational.Core.Entity.HotelRoomRate", "HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Invoice", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Customer", "Customer")
                        .WithMany("Invoice")
                        .HasForeignKey("FileCodeNo")
                        .HasPrincipalKey("FileCodeNo");

                    b.HasOne("PeaceInternational.Core.Entity.FiscalYear", "FiscalYear")
                        .WithMany("Invoice")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.InvoiceDetail", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.SectorTransport", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Sector", "Sector")
                        .WithMany("SectorTransport")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeaceInternational.Core.Entity.Transport", "Transport")
                        .WithMany("SectorTransport")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.ServiceVoucher", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Customer", "Customer")
                        .WithMany("ServiceVoucher")
                        .HasForeignKey("FileCodeNo")
                        .HasPrincipalKey("FileCodeNo");

                    b.HasOne("PeaceInternational.Core.Entity.FiscalYear", "FiscalYear")
                        .WithMany("ServiceVoucher")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeaceInternational.Core.Entity.Hotel", "Hotel")
                        .WithMany("ServiceVoucher")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("FiscalYear");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Tourcost", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Guide", "Guide")
                        .WithMany("Tourcost")
                        .HasForeignKey("GuideId");

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.TourcostDetail", b =>
                {
                    b.HasOne("PeaceInternational.Core.Entity.Hotel", "HotelA")
                        .WithMany("TourcostDetailA")
                        .HasForeignKey("HotelAId");

                    b.HasOne("PeaceInternational.Core.Entity.Hotel", "HotelB")
                        .WithMany("TourcostDetailB")
                        .HasForeignKey("HotelBId");

                    b.HasOne("PeaceInternational.Core.Entity.Hotel", "HotelC")
                        .WithMany("TourcostDetailC")
                        .HasForeignKey("HotelCId");

                    b.HasOne("PeaceInternational.Core.Entity.Sector", "Sector1")
                        .WithMany("TourcostDetail1")
                        .HasForeignKey("Sector1Id")
                        .IsRequired();

                    b.HasOne("PeaceInternational.Core.Entity.Sector", "Sector2")
                        .WithMany("TourcostDetail2")
                        .HasForeignKey("Sector2Id");

                    b.HasOne("PeaceInternational.Core.Entity.Sector", "Sector3")
                        .WithMany("TourcostDetail3")
                        .HasForeignKey("Sector3Id");

                    b.HasOne("PeaceInternational.Core.Entity.Tourcost", "Tourcost")
                        .WithMany("TourcostDetail")
                        .HasForeignKey("TourcostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelA");

                    b.Navigation("HotelB");

                    b.Navigation("HotelC");

                    b.Navigation("Sector1");

                    b.Navigation("Sector2");

                    b.Navigation("Sector3");

                    b.Navigation("Tourcost");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Customer", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("ServiceVoucher");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.FiscalYear", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Invoice");

                    b.Navigation("ServiceVoucher");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Guide", b =>
                {
                    b.Navigation("Tourcost");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Hotel", b =>
                {
                    b.Navigation("HotelRoomRate");

                    b.Navigation("ServiceVoucher");

                    b.Navigation("TourcostDetailA");

                    b.Navigation("TourcostDetailB");

                    b.Navigation("TourcostDetailC");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Sector", b =>
                {
                    b.Navigation("SectorTransport");

                    b.Navigation("TourcostDetail1");

                    b.Navigation("TourcostDetail2");

                    b.Navigation("TourcostDetail3");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Tourcost", b =>
                {
                    b.Navigation("TourcostDetail");
                });

            modelBuilder.Entity("PeaceInternational.Core.Entity.Transport", b =>
                {
                    b.Navigation("SectorTransport");
                });
#pragma warning restore 612, 618
        }
    }
}
