apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: peace-international
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=mysql.mysql.svc.cluster.local;Database=peace_international;User=peace_user;Password=Peace@123;Port=3306;"
